name: build
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.20.x]
    name: go-build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: Build the code
        run: make build